"""Added columns

Revision ID: 2f1377edc7fa
Revises: d927f727513f
Create Date: 2022-07-17 14:00:28.332680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f1377edc7fa"
down_revision = "d927f727513f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversion_job", sa.Column("export_url", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "conversion_job", sa.Column("latest_message", sa.Text(), nullable=True)
    )
    op.add_column(
        "conversion_job",
        sa.Column("latest_status", sa.String(length=16), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversion_job", "latest_status")
    op.drop_column("conversion_job", "latest_message")
    op.drop_column("conversion_job", "export_url")
    # ### end Alembic commands ###
