"""Init ConversionJob

Revision ID: 895109f208ca
Revises: 
Create Date: 2022-07-19 18:07:04.088168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "895109f208ca"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversion_job",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("origin_file_path", sa.String(length=128), nullable=True),
        sa.Column("export_file_path", sa.String(length=128), nullable=True),
        sa.Column("export_url", sa.String(length=256), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversion_job_id"), "conversion_job", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversion_job_id"), table_name="conversion_job")
    op.drop_table("conversion_job")
    # ### end Alembic commands ###
