"""empty message

Revision ID: 94ca5f6580d1
Revises: 46cfe729d1ae
Create Date: 2022-07-18 07:47:31.078614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "94ca5f6580d1"
down_revision = "46cfe729d1ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversion_job", sa.Column("deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversion_job", "deleted")
    # ### end Alembic commands ###
