"""Add print_format and projection columns

Revision ID: ad7c70a21487
Revises: 895109f208ca
Create Date: 2022-11-19 12:25:19.524770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ad7c70a21487"
down_revision = "895109f208ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversion_job", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "print_format",
                sa.Enum("A4", "US_LETTER", name="formatsenum"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "projection",
                sa.Enum(
                    "EQUIRECTANGULAR",
                    "MERCATOR",
                    "GALL_STEREOGRAPHIC",
                    name="projectionsenum",
                ),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversion_job", schema=None) as batch_op:
        batch_op.drop_column("projection")
        batch_op.drop_column("print_format")

    # ### end Alembic commands ###
